name: my_dbt_project
version: 1.0
config-version: 2

# Schema padrão para materialização
profile: default

# Diretórios do projeto
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
macro-paths: ["macros"]
seed-paths: ["data"]

# Target padrão
target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

# models:
#   my_dbt_project:
#     gold:
#       materialized: incremental  # Define materialização incremental para todos os modelos na pasta gold
