default:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: TUNOYFN-QVA43709
      user: GUSTAVOBRIETZIG
      password: '@Senha12345678'
      role: ACCOUNTADMIN          # role da sessão
      database: ITAX
      schema: DBT_CONTROL
      warehouse: COMPUTE_WH
      threads: 1                  # número de threads para execução paralela
      client_session_keep_alive: false
